baseURL: "https://time-friend.com/"
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: true
theme: "hugo-brewm"
enableGitInfo: true
enableRobotsTXT: true

module:
  mounts:
    - source: content/en
      target: content
      lang: en
    - source: content
      target: content
      lang: zh
      excludeFiles: 'en/**'

languages:
  en:
    weight: 1
    languageCode: en-GB
    languageName: English
    title: Be Your Time Friend
    params:
      description: "Keep learning, keep blogging."
    pagination:
      pagerSize: 8
      path: page
  zh:
    weight: 2
    languageCode: zh-CN
    languageName: 中文
    title: Be Your Time Friend
    params:
      description: "Keep learning, keep blogging."
    pagination:
      pagerSize: 8
      path: page

params:
  title: Be Your Time Friend
  description: "Keep learning, keep blogging."
  copyright: "Copyright 2024 © 0x1428571429"
  HideHugoCredit: true
  extMeta: true

  author:
    name: 0x1428571429
    email: incomparable9527@foxmail.com

  feed:
    flowlines: false

  posts:
    colophon: true

  logo:
    logoType: true

  search:
    enable: false
    pagefind: false

permalinks:
  archive: archive/:slug/

markup:
  goldmark:
    renderer:
      unsafe: true
  defaultMarkdownHandler: goldmark

taxonomies:
  tag: "tags"
  category: "categories"

outputs:
  home: ["HTML", "RSS", "JSON"]
